#!/usr/bin/env python3
"""Generate Kamalen GTK palette and widget geometry without replacing user CSS."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import tempfile

IMPORTS = ('@import url("kamalen-colors.css");', '@import url("kamalen-aesthetic.css");')


def color_css(p: dict[str, str]) -> str:
    names = {
        "accent_color": p["accent"], "accent_bg_color": p["accent"], "accent_fg_color": p["bg"],
        "destructive_color": p["red"], "success_color": p["green"], "warning_color": p["yellow"],
        "window_bg_color": p["bg"], "window_fg_color": p["fg"], "view_bg_color": p["surface"],
        "view_fg_color": p["fg"], "headerbar_bg_color": p["surface"], "headerbar_fg_color": p["fg"],
        "popover_bg_color": p["surface"], "popover_fg_color": p["fg"], "card_bg_color": p["surface"],
        "card_fg_color": p["fg"], "borders": p["dim"],
    }
    return "\n".join(f"@define-color {name} {value};" for name, value in names.items()) + "\n"


def aesthetic_css(profile: str, gtk_version: int) -> str:
    profiles = {
        "tui-style": dict(control=0, card=0, track=0, height=32, slider=4, thumb=0, border=1),
        "pills": dict(control=999, card=16, track=999, height=40, slider=8, thumb=999, border=0),
        "gnome-like": dict(control=8, card=12, track=999, height=40, slider=6, thumb=999, border=1),
    }
    t = profiles.get(profile, profiles["pills"])
    dropdown = "dropdown" if gtk_version == 4 else "combobox"
    return f"""/* Generated by Kamalen Shell: {profile}. */
button, entry, spinbutton, {dropdown} {{
  border-radius: {t['control']}px;
  min-height: {t['height']}px;
  border-width: {t['border']}px;
}}
notebook > header > tabs > tab, .card, popover contents {{ border-radius: {t['card']}px; }}
scale trough, progressbar trough {{ border-radius: {t['track']}px; min-height: {t['slider']}px; }}
scale highlight, progressbar progress {{ border-radius: {t['track']}px; min-height: {t['slider']}px; }}
scale slider {{ border-radius: {t['thumb']}px; min-width: 18px; min-height: 18px; }}
switch {{ border-radius: {t['track']}px; min-width: 44px; min-height: 24px; }}
switch slider {{ border-radius: {t['thumb']}px; min-width: 18px; min-height: 18px; }}
"""


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent, text=True)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def _ensure_imports(css: str) -> str:
    lines = [line for line in css.splitlines() if not any(name in line for name in ("kamalen-colors.css", "kamalen-aesthetic.css"))]
    body = "\n".join(lines).lstrip("\n")
    return "\n".join(IMPORTS) + "\n" + (body + "\n" if body else "")


def write_theme(base: Path, palette: dict[str, str], profile: str) -> None:
    for version in (3, 4):
        folder = base / f"gtk-{version}.0"
        folder.mkdir(parents=True, exist_ok=True)
        root = folder / "gtk.css"
        existing = root.read_text(encoding="utf-8") if root.exists() else ""
        _atomic_write(folder / "kamalen-colors.css", color_css(palette))
        _atomic_write(folder / "kamalen-aesthetic.css", aesthetic_css(profile, version))
        _atomic_write(root, _ensure_imports(existing))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", type=Path, default=Path.home() / ".config")
    parser.add_argument("--palette-json", required=True)
    parser.add_argument("--profile", default="pills")
    args = parser.parse_args()
    write_theme(args.base, json.loads(args.palette_json), args.profile)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
