
animations=1
layer_animations=1
animation_type_open=slide
animation_type_close=slide
animation_fade_in=1
animation_fade_out=1
tag_animation_direction=1

zoom_initial_ratio=0.90
zoom_end_ratio=1.0
fadein_begin_opacity=0.0
fadeout_begin_opacity=1.0

animation_duration_open=480
animation_duration_close=300
animation_duration_move=420
animation_duration_tag=720
animation_duration_focus=240

animation_curve_open=0.16,1.0,0.3,1.0
animation_curve_close=0.4,0.0,0.2,1.0
animation_curve_move=0.2,1.0,0.3,1.0
animation_curve_tag=0.18,1.0,0.3,1.0
animation_curve_focus=0.4,0.0,0.2,1.0
animation_curve_opafadein=0.16,1.0,0.3,1.0
animation_curve_opafadeout=0.4,0.0,0.6,1.0
