
#Autostart
exec-once=solaar -w --hide
exec-once=brwoseros
exec-once=easy-effects -w
exec-once=awww-daemon
exec-once=quickshell
exec-once=mpd-mpris
exec-once=bash ~/.config/mango/idle.sh
exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store
