
#Colors
rootcolor=0x000000ff
bordercolor=0x487ba7ff
focuscolor=0x9c8cf4ff
urgentcolor=0xde9c8aff
scratchpadcolor=0x9c8cf4ff
globalcolor=0x9c8cf4ff
overlaycolor=0x54b67bff
maximizescreencolor=0xf4f39aff
