
#Colors
rootcolor=0x000000ff
bordercolor=0x5d6559ff
focuscolor=0x6ce5d9ff
urgentcolor=0xb6af54ff
scratchpadcolor=0x6ce5d9ff
globalcolor=0x6ce5d9ff
overlaycolor=0x31d939ff
maximizescreencolor=0x83b654ff
