
#Input
repeat_rate=50
repeat_delay=300
cursor_theme=Bibata-Modern-Ice
cursor_size=34
cursor_hide_timeout=3
xkb_rules_layout=br
xkb_rules_variant=abnt2
xkb_rules_model=pc105
xkb_rules_options=caps:escape
