
# Canvas
# NOTE: unsupported by the installed MangoWM build, kept disabled to mirror clean.
# canvas_tiling=0
# canvas_pan_on_kill=1

#Overview
enable_hotarea=0
ov_tab_mode=0
overviewgappi=5
overviewgappo=30
