[General]
Background=assets/fallback-background.svg
Avatar=assets/fallback-avatar.svg
Font=JetBrainsMono Nerd Font
ClockFormat=hh:mm AP
DateFormat=dddd, d 'de' MMMM
Bg=#1e1e2e
Fg=#cdd6f4
Accent=#89b4fa
Green=#a6e3a1
Red=#f38ba8
Yellow=#f9e2af
Surface=#313244
Dim=#6c7086
DarkMode=true
BlurProfile=none
BorderRadius=16
OwnerUsername=
BlurredBackground=
